# tmux config managed by chezmoi
set -g mouse on
set -g history-limit 20000
set -g default-terminal "tmux-256color"

# Faster escape from copy mode.
set -s escape-time 0

# Reload config.
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

